version: '3.8'

services:
  api:
    build: ./api
    command: uvicorn server:app --host 0.0.0.0 --port 80
    restart: always
    volumes:
      - ./api:/code/api
    ports:
      - 80:80
    links:
      - "voicestickers_db:voicestickers_db"
    depends_on:
      - voicestickers_db

  bot:
    build: ./app
    command: python3 main.py
    restart: always
    volumes:
      - ./app:/code/app
    depends_on:
      - api

  voicestickers_db:
    build: ./postgres_database
    volumes:
      - ./postgres_database:/code/postgres_database
    ports: 
      - 5432:5432
    restart: always

    environment:
      - POSTGRES_USER=postgres_voicestickers
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=voicestickers_db
      - POSTGRES_HOST_AUTH_METHOD=trust